// Generated by CoffeeScript 1.10.0
(function() {
  var _, convert;

  convert = require('./convert');

  _ = require('lodash');

  module.exports = {
    available: function() {
      return ['miller', 'fix', 'simple', 'alternativeSimple', 'advanced', 'alternativeAdvanced', 'microbrewit'];
    },
    miller: function(og, fg) {
      var calc;
      calc = ((og - fg) / 0.75) * 100;
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    fix: null,
    simple: function(og, fg) {
      var calc;
      calc = (og - fg) * 131.25;
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    alternativeSimple: function(og, fg) {
      var calc;
      calc = (1.05 / 0.79) * (og - fg / fg) * 100;
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    advanced: function(og, fg) {
      var calc;
      calc = (og - fg) * (100.3 * (og - fg) + 125.65);
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    alternativeAdvanced: function(og, fg) {
      var calc;
      calc = (76.08 * (og - fg) / (1.775 - og)) * (fg / 0.794);
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    microbrewit: function(og, fg) {
      var calc;
      calc = (this.alternativeSimple(og, fg) + this.alternativeAdvanced(og, fg) + this.simple(og, fg) + this.advanced(og, fg) + this.miller(og, fg)) / 5;
      if (_.isNaN(calc)) {
        calc = 0;
      }
      return calc;
    },
    calc: function(og, fg, formula) {
      var calc;
      if (!this[formula]) {
        formula = 'microbrewit';
      }
      calc = this[formula](og, fg);
      if (!_.isNaN(calc)) {
        return calc;
      } else {
        return 0;
      }
    }
  };

}).call(this);
