// Generated by CoffeeScript 1.10.0
(function() {
  var convert;

  convert = require('./convert');

  module.exports = {
    available: function() {
      var available;
      available = Object.keys(this);
      available.splice(available.indexOf('available'), 1);
      return available;
    },
    mcu: function(weight, lovibond, postBoilVolume) {
      var volume;
      weight = convert.convert(weight, 'kg', 'lbs');
      volume = convert.convert(postBoilVolume, 'liters', 'gallons');
      return weight * lovibond / volume;
    },
    morey: function(calc) {
      if (calc.mcu == null) {
        calc.mcu = this.mcu(calc.weight, calc.lovibond, calc.postBoilVolume);
      }
      return 1.4922 * Math.pow(calc.mcu, 0.6859);
    },
    daniels: function(calc) {
      if (calc.mcu == null) {
        calc.mcu = this.mcu(calc.weight, calc.lovibond, calc.postBoilVolume);
      }
      return (0.2 * calc.mcu) + 8.4;
    },
    mosher: function(calc) {
      if (calc.mcu == null) {
        calc.mcu = this.mcu(calc.weight, calc.lovibond, calc.postBoilVolume);
      }
      return (0.3 * calc.mcu) + 4.7;
    }
  };

}).call(this);
