// Generated by CoffeeScript 1.10.0
(function() {
  var convert;

  convert = require('./convert');

  module.exports = {
    available: function() {
      var available;
      available = Object.keys(this);
      available.splice(available.indexOf('available'), 1);
      return available;
    },
    mcu: function(weight, lovibond, postBoilVolume) {
      var volume;
      weight = convert.convert(weight, 'kg', 'lbs');
      volume = convert.convert(postBoilVolume, 'liters', 'gallons');
      return weight * lovibond / volume;
    },
    morey: function(calcObj) {
      if (calcObj.mcu == null) {
        calcObj.mcu = this.mcu(calcObj.weight, calcObj.lovibond, calcObj.postBoilVolume);
      }
      return 1.4922 * Math.pow(calcObj.mcu, 0.6859);
    },
    daniels: function(calcObj) {
      if (calcObj.mcu == null) {
        calcObj.mcu = this.mcu(weight, lovibond, postBoilVolume);
      }
      return (0.2 * calcObj.mcu) + 8.4;
    },
    mosher: function(calcObj) {
      if (calcObj.mcu == null) {
        calcObj.mcu = this.mcu(weight, lovibond, postBoilVolume);
      }
      return (0.3 * calcObj.mcu) + 4.7;
    }
  };

}).call(this);
