// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = {
    abv: require('./abv'),
    bitterness: require('./bitterness'),
    colour: require('./colour'),
    color: this.colour,
    convert: require('./convert')
  };

}).call(this);
